//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherStation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherStation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;00501&quot;,&quot;+40.922326&quot;,&quot;-072.637078&quot;,&quot;HOLTSVILLE&quot;,&quot;NY&quot;,&quot;SUFFOLK&quot;,&quot;UNIQUE&quot;
        ///&quot;00544&quot;,&quot;+40.922326&quot;,&quot;-072.637078&quot;,&quot;HOLTSVILLE&quot;,&quot;NY&quot;,&quot;SUFFOLK&quot;,&quot;UNIQUE&quot;
        ///&quot;00601&quot;,&quot;+18.165273&quot;,&quot;-066.722583&quot;,&quot;ADJUNTAS&quot;,&quot;PR&quot;,&quot;ADJUNTAS&quot;,&quot;STANDARD&quot;
        ///&quot;00602&quot;,&quot;+18.393103&quot;,&quot;-067.180953&quot;,&quot;AGUADA&quot;,&quot;PR&quot;,&quot;AGUADA&quot;,&quot;STANDARD&quot;
        ///&quot;00603&quot;,&quot;+18.455913&quot;,&quot;-067.145780&quot;,&quot;AGUADILLA&quot;,&quot;PR&quot;,&quot;AGUADILLA&quot;,&quot;STANDARD&quot;
        ///&quot;00604&quot;,&quot;+18.493520&quot;,&quot;-067.135883&quot;,&quot;AGUADILLA&quot;,&quot;PR&quot;,&quot;AGUADILLA&quot;,&quot;STANDARD&quot;
        ///&quot;00605&quot;,&quot;+18.465162&quot;,&quot;-067.141486&quot;,&quot;AGUADILLA&quot;,&quot;PR&quot;,&quot;AGUADILLA&quot;,&quot;STAND [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZipCodeTable {
            get {
                return ResourceManager.GetString("ZipCodeTable", resourceCulture);
            }
        }
    }
}
